version: '3.0'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: dev.Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - "27018:27017"
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
      ME_CONFIG_MONGODB_URL: mongodb://root:dev@mongo:27017/
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
    driver: local
