openapi: 3.0.0
info:
  title: Book Management API
  description: API for managing books in a bookstore
  version: 1.0.0

paths:
  /books:
    get:
      summary: Retrieve a list of books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Invalid input
  /books/{id}:
    get:
      summary: Retrieve a book by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the book to retrieve
      responses:
        '200':
          description: Book details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
    put:
      summary: Update a book by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the book to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookUpdate'
      responses:
        '200':
          description: Book updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Invalid input
        '404':
          description: Book not found
    delete:
      summary: Delete a book by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the book to delete
      responses:
        '204':
          description: Book deleted successfully
        '404':
          description: Book not found

components:
  schemas:
    Book:
      type: object
      required:
        - title
        - isbn
        - price
        - author
        - category
      properties:
        title:
          type: string
          description: The title of the book
        isbn:
          type: string
          description: The ISBN of the book
        price:
          type: number
          format: float
          description: The price of the book
        author:
          type: string
          description: The author of the book
        category:
          type: string
          description: The category of the book
    BookUpdate:
      type: object
      properties:
        title:
          type: string
          description: The title of the book
        isbn:
          type: string
          description: The ISBN of the book
        price:
          type: number
          format: float
          description: The price of the book
        author:
          type: string
          description: The author of the book
        category:
          type: string
          description: The category of the book
